### ISSUE TITLE
pydpiper 1.13.1 registration_chain.py, "_to_common.mnc" files missing

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#203] opened 2015-03-31 20:16 UTC
According to https://wiki.mouseimaging.ca/display/MICePub/Longitudinal+Registration+Tools I should be able to QC registration_chain.py by looking for files
<subject>/resampled/*_to_common.mnc which should be the subject transformed into the common space.

In my case, I ran registration_chain.py with:
```
registration_chain.py --num-executors=48 \
    --verbose --pipeline-name=D2KO \
    --avg-time-point 1 \
    --common-space-name baseline \
    --init-model ../../atlas/c57_140micron.mnc \
    --lsq6-large-rotations \
    --lsq6-large-rotations-parameters mousebrain \
    --lsq12-subject-matter mousebrain \
    --config-file /project/j/jlerch/matthijs/pydpiper_modules/pydpiper-master-v1.13.1/python/pydpiper-1.13.1-py2.7.egg/config/SciNet.cfg \
    D2KO-registration-chain-input.csv
```

Based on this, I should be expecting files named "*_to_baseline.mnc". My D2KO_nlin directory does contain files called "baseline-nlin-n.mnc" but my subjects don't seem to be resampled to the common space.

**Comment by mcvaneede** [comment] 2015-04-01 14:31
Correct. The registration_chain.py is still under development. The official releases don't actually include the latest changes to the registration chain yet. The reason for this is that we are still testing and verifying that the correct statistics files are created. 

The instructions on the wiki apply to the current develop branch which we have installed at MICe, and which we are testing at the moment.

**Comment by gdevenyi** [comment] 2015-04-01 17:06
Ah I see, is this the same as the code available in the develop branch or is this still internal?

Is the state of registration_chain sufficient for application in the current 1.13.1 release, or should I be re-structuring my study to use MBM?

**Comment by mcvaneede** [comment] 2015-04-01 18:34
The develop branch is up-to-date. The latest commit there is what we are using here.

With the registration_chain code that is part of 1.13.1, the one thing I am not 100% sure about is whether the stats files that are created are always correct. So if you are using 1.13.1 and want to use the registration_chain, you need to check that the stats files you are analyzing have been calculated from the correct transformation.

**Comment by bcdarwin** [comment] 2015-04-01 18:37
Also note that develop is installed at SciNet and loadable as `pydpiper/dev`.  There's no guarantees it will run, so it's probably best not to test it on huge pipelines at the moment.

**Comment by gdevenyi** [comment] 2015-04-01 18:41
Thanks @mcvaneede , I'll take a close look at the results before we trust them.

@bcdarwin Thanks, I was just looking at that, it seems that the software is installed in your home dir so right now group mchakrav doesn't have access to it. If you could grant access, I would love to test it on a smaller set of my data. Thanks!

**Comment by bcdarwin** [comment] 2015-04-01 18:52
@gdevenyi Done

**Comment by gdevenyi** [comment] 2015-04-01 19:30
Thanks, but seems it doesn't quite work yet:
```
gpc-f102n084-ib0-$ ls /home/j/jlerch/bcdarwin/pydpiper-dev/lib/python2.7/site-packages
ls: cannot access /home/j/jlerch/bcdarwin/pydpiper-dev/lib/python2.7/site-packages: Permission denied
gpc-f102n084-ib0-$ ls /home/j/jlerch/bcdarwin/pydpiper-dev/bin
ls: cannot access /home/j/jlerch/bcdarwin/pydpiper-dev/bin: Permission denied
```

I think this is what you'll need to run
```
setfacl -R -m  "g:mchakrav:rX" /home/j/jlerch/bcdarwin/pydpiper-dev
setfacl -R -m  "g:mchakrav:rX" /home/j/jlerch/bcdarwin/git/pydpiper/
```

**Comment by bcdarwin** [comment] 2015-04-01 19:59
I think the problem is that you need `rx` on /home/j/jlerch/ and /home/j/jlerch/bcdarwin, not that you need the git repo.  Hopefully fixed now (note I've moved the install from /home to /project, but that shouldn't matter).

**Comment by gdevenyi** [comment] 2015-04-01 20:09
Cheers, working now!

**Closed** 2015-04-01 20:10 UTC
