### ISSUE TITLE
Improve output directory/naming structure

### ISSUE THREAD

**Issue by bcdarwin** [Mouse-Imaging-Centre/pydpiper#114] opened 2014-09-10 15:45 UTC
We might name the `init_model`, `pydpiper-backups` directories with the value of `--pipeline-name` as is done for the other directories created, and/or timestamp these directories.

Also, we might create a new directory for logs to avoid cluttering the cwd.

**Comment by jasonlerch** [comment] 2015-02-10 21:37
Duplicate of #164

**Closed by jasonlerch** 2015-02-10 21:37 UTC
