### ISSUE TITLE
pydpiper only takes one lsq12 protocol

### ISSUE THREAD

**Issue by nzxwang** [Mouse-Imaging-Centre/pydpiper#429] opened 2019-07-29 21:17 UTC
ValueError: 

You have specified a different lsq12 protocol for MAGeT as compared to the lsq12 protocol for the main registration: 

--maget-lsq12-protocol /hpf/largeprojects/MICe/nwang/collaborator_40um/2019-06-21_Picketts_Snf2H-Snf2L/linear_MAGeT_prot.csv
--lsq12-protocol /hpf/largeprojects/MICe/tools/protocols/linear/Pydpiper_testing_default_lsq12.csv

One lsq12 protocol can be used for both parts of the pipeline. Please decide which of the two you want to use, and specify only that one using the --lsq12-protocol flag.

**Comment by bcdarwin** [comment] 2019-07-31 17:38
duplicate of #266

**Closed by bcdarwin** 2019-07-31 17:38 UTC
