### ISSUE TITLE
MBM.py strips "resampled" out of input file names that originally had that name

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/pydpiper#155] opened 2014-11-25 18:52 UTC
In ``_processed`` directory:

```
$ ls
A10FISP2_SC.anlm_denoise.n4correct.nuyl-avgmodel-all.resampled
...
```
This is correct and my original input filename.

However when I look at the files in ``stats-volumes``
```
$ ls
A10FISP2_SC.anlm_denoise.n4correct.nuyl-avgmodel-all-final-nlin_with_additional_inverted_absolute_log_determinant.mnc
...
```

The ``.resampled`` component of the original filename has been stripped off.

This difference in output name breaks processing scripts down the line which rely on the naming.

**Comment by jasonlerch** [comment] 2015-02-10 21:21
Duplicate of #168

**Closed by jasonlerch** 2015-02-10 21:21 UTC
